# Generated by Django 5.1.3 on 2024-12-19 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(verbose_name="Цена"),
        ),
    ]
