# Generated by Django 5.1.5 on 2025-01-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_category_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
